### ISSUE TITLE
Issue when make build

### ISSUE THREAD

**Issue by punyahenry** [dimaskiddo/go-whatsapp-multidevice-gpt#1]
$ make build
go: downloading github.com/sashabaranov/go-openai v1.10.0
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/stretchr/testify v1.2.2
go: downloading github.com/google/go-cmp v0.5.5
go: downloading golang.org/x/tools v0.0.0-20201124115921-2c860bdd6e78
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/mod v0.3.0
# sort
/usr/local/go/src/sort/zsortfunc.go:10:6: insertionSort_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:10:6: other declaration of insertionSort_func
/usr/local/go/src/sort/zsortfunc.go:20:6: siftDown_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:19:6: other declaration of siftDown_func
/usr/local/go/src/sort/zsortfunc.go:38:6: heapSort_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:38:6: other declaration of heapSort_func
/usr/local/go/src/sort/zsortfunc.go:329:6: swapRange_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:65:6: other declaration of swapRange_func
/usr/local/go/src/sort/zsortfunc.go:335:6: stable_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:163:6: other declaration of stable_func
/usr/local/go/src/sort/zsortfunc.go:378:6: symMerge_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:187:6: other declaration of symMerge_func
/usr/local/go/src/sort/zsortfunc.go:464:6: rotate_func redeclared in this block
        /usr/local/go/src/sort/zfuncversion.go:252:6: other declaration of rotate_func
Makefile:35: recipe for target 'build' failed
make: *** [build] Error 1

$ go version
go version go1.20.5 linux/amd64

**Comment by dimaskiddo** [comment]
@punyahenry i think the conflict is from your go installataion src not from this source code, may be you need to clean install your go
